from matplotlib import markers
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("../data/student-mat.csv", sep=";")
# plt.hist(df["age"],bins=8)
# plt.title("Age distrubution for students")
# plt.xlabel("Age")
# # plt.ylabel("Number of Students")
# # plt.savefig("age_histogram.png")
# plt.boxplot(df["age"])
# plt.show()
print("describe is :")
print(df["studytime"].describe())
print("now value_count : ")
print(df["studytime"].value_counts())
hello = df["studytime"].value_counts()
plt.bar(hello.index, hello.values)
plt.title("graph of study_time")
plt.xlabel("studytime_categories")
plt.ylabel("number of students")
plt.show()
